name: Build App2

on:
  push:
    tags:
      - 'app2-v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install Nx dependencies
        run: npm install -g @nrwl/workspace @nrwl/next
      - name: Install Nx global 
        run: sudo npm install -g nx@latest
      - name: Install project dependencies
        working-directory: ./
        run: npm install

      - name: Init submodule
        run: git submodule init
      - name: Update submodule app2
        run: git submodule update --remote apps/app2

      - name: Build app 1 start...
        run: nx run app2:build